#!/bin/bash
# .bdx.0100.y.llama.main.run_and_profile.sh
# 20230910_225422




set -x;
_ts="date +%Y%m%d_%H%M%S";
_tmp_bdx_d=".tmp.bdx.d";
mkdir -p $_tmp_bdx_d;




###
### STAR: profiling
###
### https://docs.python.org/3/library/profile.html
### https://medium.com/@narenandu/profiling-and-visualization-tools-in-python-89a46f578989
### https://pytorch.org/tutorials/recipes/recipes/profiler_recipe.html
###
_tmp_star_d=".tmp.star.d";
mkdir -p $_tmp_star_d;
_tstamp="$($_ts)";
_star_prof_out_bin=".star.prof_out.bin"; # generated by (prof).dump_stats('.star.prof_out.bin') or python -m cProfile -o test.pstats test.py
_star_prof_out_txt=".star.prof_out.${_tstamp}.txt"; # generated by (pstats).print_stats()
_star_prof_out_svg=".star.prof_out.${_tstamp}.svg"; # generated by gprof2dot
_viztr_tracer_output="${_tmp_star_d}/.star.prof_out.${_tstamp}.json"; # generated by viztracer
_viztr_tracer_entries="100000000";




###
### Check prerequisites: execution environment (venv, torch-for-cpu)
###
echo "### Let me check where 'torchrun' is:  '$(which torchrun)'";   ### Litmus test to check the virtual environment
read -p "### Do we need to (re-)install all things required? [y|N] " _answer;
if [ "X$_answer" = "Xy" ]; then
	python -m venv .env;
	source .env/bin/activate; ### must do
	python -m pip install --upgrade pip;
	python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu;
	python -m pip install gprof2dot; ### python profiling and visualization
	python -m pip install snakeviz; ### python profiling and visualization
	python -m pip install viztracer; ### python profiling and visualization
	#python -m pip install pycscope;
	#python -m pip install pycallgraph; ### python profiling and visualization ### ERROR?
	python -m pip install -e .;
	if [ "X$(basename $(which eog))" != "Xeog" ]; then
		sudo apt install eog;
	fi
	echo $_tstamp > ${_tmp_bdx_d}/.flag.venv.created;
	echo $_tstamp > ${_tmp_bdx_d}/.flag.pkg.installed;
else
	source .env/bin/activate; ### must do
fi

###
### Check prerequisites: good download of tokenizer.model
###
if [ -f ${_tmp_bdx_d}/.flag.venv.created -a -f ${_tmp_bdx_d}/.flag.pkg.installed ]; then
	echo "### GOOD: execution environment (as a prerequisite) is ready";
	_chksum_tokenizer_ref="eeec4125e9c7560836b4873b6f8e3025";
	_chksum_tokenizer_test="$( cat tokenizer.model | md5sum | awk '{ print $1 }' )";
	if [ "X$_chksum_tokenizer_ref" = "X$_chksum_tokenizer_test" ]; then
		echo "### GOOD: tokenizer.model checksum matches the reference value";
	else
		echo "### ERROR: tokenizer.model checksum does not match -- EXIT 18";
		exit 18;
	fi
else
	echo "### ERROR: execution environment is not ready -- EXIT 18";
	exit 18;
fi




###
### parameters to control the test
###
_nproc_per_node="1";		# 1
_ckpt_dir="llama-2-7b/";	# "llama-2-7b/"
_max_seq_len="128";		# 128
_max_batch_size="1";		# 1




###
### functions
###

function main_exec_profiling_with_viztracer()
{
	_main_python_file_with_viztracer="example_text_completion.star.viztracer.py";   ### _main_python_file="example_text_completion.py";
	# python -m viztracer --tracer_entries $_viztr_tracer_entries -o $_viztr_tracer_output \
	torchrun --nproc_per_node $_nproc_per_node $_main_python_file_with_viztracer --ckpt_dir $_ckpt_dir  --tokenizer_path tokenizer.model --max_seq_len $_max_seq_len --max_batch_size $_max_batch_size ;
}

function main_exec_profiling_with_cprofile()
{
	_main_python_file_with_cprofile="example_text_completion.star.cprofile.py";   ### _main_python_file="example_text_completion.py";
	# python -m viztracer --tracer_entries $_viztr_tracer_entries -o $_viztr_tracer_output \
	torchrun --nproc_per_node $_nproc_per_node $_main_python_file_with_cprofile --ckpt_dir $_ckpt_dir  --tokenizer_path tokenizer.model --max_seq_len $_max_seq_len --max_batch_size $_max_batch_size ;
	( cd $_tmp_star_d; 
	gprof2dot -f pstats $_star_prof_out_bin | dot -Tsvg -o $_star_prof_out_svg;
	eog $_star_prof_out_svg &
	snakeviz $_star_prof_out_bin &
	#read -p "### Do you want to see ${_star_prof_out_svg} via eog? [Y|n] " _answer;
	#if [ "X$_answer" = "Xy" ]; then
	#	eog $_star_prof_out_svg &
	#fi
	#read -p "### Do you want to see ${_star_prof_out_bin} via snakeviz? [Y|n] " _answer;
	#if [ "X$_answer" = "Xy" ]; then
	#	snakeviz $_star_prof_out_bin &
	#fi
	)
}




###
### Main
###
main_exec_profiling_with_cprofile;
main_exec_profiling_with_viztracer;




###
### Main Old History
###
# torchrun --nproc_per_node 1 example_text_completion.py --ckpt_dir llama-2-7b/  --tokenizer_path tokenizer.model --max_seq_len 128 --max_batch_size 1
# torchrun --nproc_per_node $_nproc_per_node --ckpt_dir $_ckpt_dir  --tokenizer_path tokenizer.model --max_seq_len $_max_seq_len --max_batch_size $_max_batch_size $_main_python_file   ### ERROR: this order of arguments does not work
# python -m viztracer --tracer_entries 100000000 -o .tmp.star.d/.star.prof_out.2.json torchrun --nproc_per_node 1 example_text_completion.star.py --ckpt_dir llama-2-7b/ --tokenizer_path tokenizer.model --max_seq_len 128 --max_batch_size 1




###
### Help
###
print_help()
{
	echo "[https://github.com/facebookresearch/llama Llama 2]";
	echo "[https://github.com/krychu/llama Llama 2 on CPU, and Mac M1/M2 GPU]";
	echo "[https://github.com/facebookresearch/llama/issues/436#issuecomment-1650001563 RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found? #436]";
}




